frequency: 5
celerity: 1
res: 64
L: 0.5
pml_size: 0.25
pml_dampling: 5
rff: 512
model: 'rff'
device: 'cuda:0'
grad_norm: False
lr_gnorm: 0.01
step_size: 20
input_dim: 3
hidden_dim: 512
output_dim: 2
num_layers: 3
do_skip: True
first_omega: 30.
hidden_omega: 30.
sigma_fourier: 1.
mu: 1.
sigma: 0.1
adam: 
  lr: 0.0001
  epochs: 40000
  n_scheduler: 15000
  gamma: 0.5
  batch_size: 8192
  batch_boundary: 8192
  keeping_time: 25

fine:
  lr: 1.
  epochs: 200
  n_scheduler: 1000
  gamma: 0.2
  batch_size: 32768
  batch_boundary: 32768
  keeping_time: 3
  max_iter: 25

lora:
  lr: .1
  epochs: 200
  n_scheduler: 1000
  gamma: 0.2
  batch_size: 32768
  batch_boundary: 32768
  keeping_time: 3
  max_iter: 25