#PHISK parameters
r: 12
hidden_dims : [128,256,512]
num_fourier_features : 64

#Training parameters
adam: 
  lr: 0.00001
  epochs: 100000
  n_scheduler: 15000
  gamma: 0.5
  batch_size_dir: 8
  batch_size: 4096
  keeping_time: 25
  direction_keeping_time: 10

#Only if needed
fine:
  lr: .1
  epochs: 500
  n_scheduler: 500
  gamma: 0.5
  batch_size: 4096
  batch_size_dir: 8
  batch_boundary: 4096
  keeping_time: 5
  direction_keeping_time: 3
  max_iter: 20