r: 4
hidden_features: 64
num_hlayers: 2
omega_init: 30.0
omega_0: 30.0
device: 'cuda:0'
adam: 
  lr: 0.00001
  epochs: 100000
  n_scheduler: 15000
  gamma: 0.5
  batch_size_dir: 8
  batch_size: 8192
  keeping_time: 25
  direction_keeping_time: 10

fine:
  lr: .1
  epochs: 500
  n_scheduler: 500
  gamma: 0.5
  batch_size: 8192
  batch_size_dir: 8
  batch_boundary: 8192
  keeping_time: 2
  direction_keeping_time: 3
  max_iter: 20