#Simulation parameters
frequency: 1000
celerity: 343
ref_direction : [1.,1.]
res: 512

#Geometry parameters
L: 0.5
pml_size: 0.25
pml_dampling: 5
shape : 'circle'
mesh_param:
  r: 0.2
  center: [0.0, 0.0]
  length : .25
  n_elem : 128
  num_points : 5
  inner_radius : 0.1
  outer_radius : 0.3
  rotation : 0.
  epsilon : 1e-2
  ax:  0.15
  ay: 0.3


#Model parameters
rff: 512
input_dim: 2
hidden_dim: 64
output_dim: 2
num_layers: 3
first_omega: 30.
hidden_omega: 30.
sigma_fourier: 1.

#Training parameters
adam: 
  lr: 0.0001
  epochs: 25000
  n_scheduler: 15000
  gamma: 0.5
  batch_size:  8192
  batch_boundary: 4096
  keeping_time: 25

fine:
  lr: .1
  epochs: 250
  n_scheduler: 500
  gamma: 0.2
  batch_size: 32768
  batch_boundary: 8192
  keeping_time: 3
  max_iter: 25

lora:
  lr: 1.
  epochs: 200
  n_scheduler: 500
  gamma: 0.2
  batch_size: 32768
  batch_boundary: 8192
  keeping_time: 3
  max_iter: 25