#PHISK parameters
r: 12
hidden_dims : [128,256,512]

#Training parameters
adam: 
  lr: 0.00001
  epochs: 100000
  n_scheduler: 15000
  gamma: 0.5
  batch_size_dir: 24
  batch_size: 8192
  keeping_time: 30
  direction_keeping_time: 20

#Only if needed
fine:
  lr: .1
  epochs: 5
  n_scheduler: 500
  gamma: 0.5
  batch_size: 16384
  batch_size_dir: 12
  batch_boundary: 8192
  keeping_time: 5
  direction_keeping_time: 3
  max_iter: 20